# SPDX-FileCopyrightText: Copyright (c) OpenGeoSys Community (opengeosys.org)
# SPDX-License-Identifier: BSD-3-Clause

# %%
from pathlib import Path

import gmsh
import ogstools as ot
import pyvista as pv


# %%
class TwoJointsEFPMMesh:
    """Mesh generator for geo2d.geo (generated by geo2py).

    Converted via the gmsh unroll path, because the source uses constructs
    that are expanded before conversion (Coherence).  The geometry is
    exact, but the original .geo parameters are not exposed as arguments.

    Geometry: 12 points, 16 curves, 5 surfaces.
    Physical groups: FRACTURE, ROCK.
    """

    def __init__(self, gmsh_model, cl__1=1):
        # cl__1 = 1
        self.gmsh_model = gmsh_model

        if not gmsh.isInitialized():
            gmsh.initialize()

        self.out_dir = None

        geo = gmsh.model.geo

        # Entities, keyed by their tag in the original .geo file.
        p, c, cl, s, sl, v = {}, {}, {}, {}, {}, {}

        # --- Points (keys are the tags of the original .geo file) ---
        coords = {
            1: (0.1, 0),
            2: (12.6, 0),
            3: (12.6, 1),
            4: (0.1, 1),
            5: (12.6, 0.3),
            6: (12.6, 0.301),
            7: (0.1, 0.3),
            8: (0.1, 0.301),
            9: (12.6, 0.7),
            10: (12.6, 0.701),
            11: (0.1, 0.7),
            12: (0.1, 0.701),
        }
        for tag, (x, y) in coords.items():
            p[tag] = geo.addPoint(x, y, 0.0, cl__1, tag)

        # --- Curves (keys are the tags of the original .geo file) ---
        lines = {  # start, end
            1: (1, 2),
            2: (2, 5),
            3: (1, 7),
            4: (7, 5),
            5: (5, 6),
            6: (7, 8),
            7: (8, 6),
            8: (8, 11),
            9: (11, 9),
            10: (6, 9),
            11: (11, 12),
            12: (12, 10),
            13: (9, 10),
            14: (12, 4),
            15: (4, 3),
            16: (10, 3),
        }
        for tag, pts in lines.items():
            c[tag] = geo.addLine(*(p[t] for t in pts), tag)

        # --- Surfaces ---
        # A negative tag reverses the curve, as in the .geo file.
        loops = {
            1: [-3, 1, 2, -4],
            2: [-7, -6, 4, 5],
            3: [-8, 7, 10, -9],
            4: [-12, -11, 9, 13],
            5: [-14, 12, 16, -15],
        }
        for tag, tags in loops.items():
            cl[tag] = geo.addCurveLoop([c[t] if t > 0 else -c[-t] for t in tags], tag)

        surfaces = {
            1: [1],
            2: [2],
            3: [3],
            4: [4],
            5: [5],
        }
        for tag, tags in surfaces.items():
            s[tag] = geo.addPlaneSurface(
                [cl[t] if t > 0 else -cl[-t] for t in tags], tag
            )

        # --- Transfinite setup ---
        for tag in (1,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (2,):
            geo.mesh.setTransfiniteCurve(c[tag], 15, "Progression", 0.72)
        for tag in (3,):
            geo.mesh.setTransfiniteCurve(c[tag], 15, "Progression", 0.72)
        for tag in (4,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (5,):
            geo.mesh.setTransfiniteCurve(c[tag], 2, "Progression", 1)
        for tag in (6,):
            geo.mesh.setTransfiniteCurve(c[tag], 2, "Progression", 1)
        for tag in (7,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (8,):
            geo.mesh.setTransfiniteCurve(c[tag], 25, "Bump", 0.015)
        for tag in (9,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (10,):
            geo.mesh.setTransfiniteCurve(c[tag], 25, "Bump", 0.015)
        for tag in (11,):
            geo.mesh.setTransfiniteCurve(c[tag], 2, "Progression", 1)
        for tag in (12,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (13,):
            geo.mesh.setTransfiniteCurve(c[tag], 2, "Progression", 1)
        for tag in (14,):
            geo.mesh.setTransfiniteCurve(c[tag], 15, "Progression", 1.35)
        for tag in (15,):
            geo.mesh.setTransfiniteCurve(c[tag], 35, "Progression", 1)
        for tag in (16,):
            geo.mesh.setTransfiniteCurve(c[tag], 15, "Progression", 1.35)
        geo.mesh.setTransfiniteSurface(s[1])
        for tag in (1,):
            geo.mesh.setRecombine(2, s[tag])
        geo.mesh.setTransfiniteSurface(s[2])
        for tag in (2,):
            geo.mesh.setRecombine(2, s[tag])
        geo.mesh.setTransfiniteSurface(s[3])
        for tag in (3,):
            geo.mesh.setRecombine(2, s[tag])
        geo.mesh.setTransfiniteSurface(s[4])
        for tag in (4,):
            geo.mesh.setRecombine(2, s[tag])
        geo.mesh.setTransfiniteSurface(s[5])

        # --- Boundaries (names as in geo2d.geo) ---
        self.surfaces = [s[t] for t in range(1, 6)]
        self.fracture_surface = [s[t] for t in (2, 4)]
        self.rock_surface = [s[t] for t in (1, 3, 5)]

        # (dim, entity tags, physical tag, name), registered by
        # generate_meshes.  The bulk group is first and is always
        # named "domain", which is what OGS expects.
        self.physical_groups = [
            (2, self.surfaces, 1, "domain"),
            (2, self.fracture_surface, None, "FRACTURE"),
            (2, self.rock_surface, None, "ROCK"),
        ]

        # --- Synchronize ---
        self.gmsh_model.geo.synchronize()

    def generate_meshes(self, out_dir="", order=1):
        self.out_dir = Path(out_dir)
        if not self.out_dir.exists():
            self.out_dir.mkdir(parents=True)

        gmsh.option.setNumber("Mesh.Algorithm", 5)
        gmsh.option.setNumber("Mesh.Format", 1)

        # Always mesh linear in Gmsh; order-2 meshes are produced below via
        # createQuadraticMesh, because ot.cli().NodeReordering does not work for
        # higher order elements generated from Gmsh.
        # Set explicitly, because ~/.gmsh-options may set Mesh.ElementOrder = 2.
        gmsh.option.setNumber("Mesh.ElementOrder", 1)

        # --- Mesh generation ---
        self.gmsh_model.mesh.generate(2)

        # Optional GUI
        # if "-nopopup" not in sys.argv:
        #    gmsh.fltk.run()

        self.gmsh_model.removePhysicalGroups()
        bulk_mesh_name = "domain"
        for dim, tags, physical_tag, name in self.physical_groups:
            named = {} if name is None else {"name": name}
            self.gmsh_model.addPhysicalGroup(
                dim, tags, -1 if physical_tag is None else physical_tag, **named
            )
        bulk_mesh_name = Path(self.out_dir, bulk_mesh_name + ".vtu")

        # Set output format to MSH2
        gmsh.option.setNumber("Mesh.MshFileVersion", 2.2)
        mesh_name = "domain.msh"
        mesh_file_name = Path(self.out_dir, mesh_name)
        gmsh.write(str(mesh_file_name))

        # `dim` is ommitted for converting all meshes
        meshes = ot.Meshes.from_gmsh(mesh_file_name)

        vtu_names = []
        for name, mesh in meshes.items():
            print(f"{name}: {mesh.n_cells} cells")
            if "physical_group_" in name:
                vtu_name = Path(
                    self.out_dir, f"{name.replace('physical_group_', '')}.vtu"
                )
            else:
                vtu_name = Path(self.out_dir, f"{name}.vtu")
            vtu_names.append(vtu_name)
            pv.save_meshio(vtu_name, mesh)

        ot.cli().NodeReordering("-i", bulk_mesh_name, "-o", bulk_mesh_name)
        if order == 2:
            files_to_process = {bulk_mesh_name, *vtu_names}
            for vtu_file_name in files_to_process:
                print(f"Create quadratic mesh for {vtu_file_name}")
                ot.cli().createQuadraticMesh("-i", vtu_file_name, "-o", vtu_file_name)

        ot.cli().identifySubdomains(
            "-m",
            bulk_mesh_name,
            f"-o {self.out_dir}/",
            "-f",
            "-s 1e-6",
            "--",
            *vtu_names,
        )


# %%
if __name__ == "__main__":
    gmsh.initialize(readConfigFiles=False)
    gmsh.model.add("two_joints_EFPM")
    generator = TwoJointsEFPMMesh(gmsh.model)
    generator.generate_meshes(out_dir="02_LIE_EFPM_Fault-Controlled_Injection/input_meshes_two_joints_EFP")
    gmsh.finalize()
